[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NEXT_USE_NETLIFY_EDGE = "true"
  NODE_VERSION = "16"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/next_server"
  status = 200
  force = true
